# Generated by Django 3.2 on 2023-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='Your Default Description', max_length=500),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Default Title', max_length=150),
        ),
    ]
